#! /bin/bash

#DSK=$PWD
DSK=/opt/gitlab_ldap_group_sync
ACT_DSK="-v $DSK/actions:/app/actions"
CFG_DSK="-v $DSK/config:/app/config"
LOG_DSK="-v $DSK/log:/app/log"

docker run $ACT_DSK $CFG_DSK $LOG_DSK  -p 8000:80 gitlab-ldap-group-sync $1 
